#include "opcodes.h"
#include <string.h>
#include <assert.h>
#include "helper.h"

//constants

//config
const char *RYVM_CONFIG_MAX_STACK = ".max_stack_size";
//code
const char *RYVM_CODE_HEADER = ".text";

//const char *RYVM_CONST_DATA_HEADER = ".const"; //immutable version of .data
const char *RYVM_DATA_HEADER = ".data";

const char *RYVM_DATA_BYTE_HEADER = ".eword";
const char *RYVM_DATA_2BYTE_HEADER = ".qword";
const char *RYVM_DATA_4BYTE_HEADER = ".hword";
const char *RYVM_DATA_8BYTE_HEADER = ".word";

const char *RYVM_DATA_2BYTE_FLOAT_HEADER = ".qwordf";
const char *RYVM_DATA_4BYTE_FLOAT_HEADER = ".hwordf";
const char *RYVM_DATA_8BYTE_FLOAT_HEADER = ".wordf";

const char *RYVM_DATA_ASCIZ_HEADER = ".asciz";


//we are using macro wizardtry so that if we rename our opcodes,
//we can simply change one of the RYVM_OP_STR_... macros rather than
//going to both the str_to_op and op_to_str functions.


#define RYVM_OP_STR_NOP NOP
#define RYVM_OP_STR_MOV MOV
#define RYVM_OP_STR_LDR LDR
#define RYVM_OP_STR_PCA PCA
#define RYVM_OP_STR_LDI LDI
#define RYVM_OP_STR_STR STR
#define RYVM_OP_STR_PUSH PUSH
#define RYVM_OP_STR_POP POP
#define RYVM_OP_STR_ADD ADD
#define RYVM_OP_STR_SUB SUB
#define RYVM_OP_STR_MUL MUL
#define RYVM_OP_STR_MULU MULU
#define RYVM_OP_STR_DIV DIV
#define RYVM_OP_STR_DIVU DIVU
#define RYVM_OP_STR_MOD MOD
#define RYVM_OP_STR_MODU MODU
#define RYVM_OP_STR_ADDF ADDF
#define RYVM_OP_STR_SUBF SUBF
#define RYVM_OP_STR_MULF MULF
#define RYVM_OP_STR_DIVF DIVF
#define RYVM_OP_STR_MODF MODF
#define RYVM_OP_STR_AND AND
#define RYVM_OP_STR_OR OR
#define RYVM_OP_STR_XOR XOR
#define RYVM_OP_STR_NOT NOT
#define RYVM_OP_STR_SHL SHL
#define RYVM_OP_STR_SHR SHR
#define RYVM_OP_STR_BIC BIC
#define RYVM_OP_STR_EQ EQ
#define RYVM_OP_STR_NE NE
#define RYVM_OP_STR_GTS GTS
#define RYVM_OP_STR_LTS LTS
#define RYVM_OP_STR_GES GES
#define RYVM_OP_STR_LES LES
#define RYVM_OP_STR_GTU GTU
#define RYVM_OP_STR_LTU LTU
#define RYVM_OP_STR_GEU GEU
#define RYVM_OP_STR_LEU LEU
#define RYVM_OP_STR_EQF EQF
#define RYVM_OP_STR_NEF NEF
#define RYVM_OP_STR_GTF GTF
#define RYVM_OP_STR_LTF LTF
#define RYVM_OP_STR_GEF GEF
#define RYVM_OP_STR_LEF LEF
#define RYVM_OP_STR_JMP JMP
#define RYVM_OP_STR_JMPF JMPF
#define RYVM_OP_STR_JMPT JMPT
#define RYVM_OP_STR_CALL CALL
#define RYVM_OP_STR_RET RET
#define RYVM_OP_STR_END END
#define RYVM_OP_STR_SYS SYS





#define RYVM_OPCODE_STR(s, op, res) if(strcmp(s, RYVM_STR(op)) == 0) { *code = RYVM_CON(RYVM_OP_, op); return 1;}

int ryvm_opcode_str_to_op(const char *s, enum ryvm_opcode *code) {
  RYVM_OPCODE_STR(s, RYVM_OP_STR_NOP, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MOV, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LDR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_PCA, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LDI, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_STR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_PUSH, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_POP, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_ADD, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SUB, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MUL, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MULU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_DIV, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_DIVU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MOD, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MODU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_ADDF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SUBF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MULF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_DIVF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MODF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_AND, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_OR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_XOR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_NOT, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SHL, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SHR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_BIC, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_EQ, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_NE, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GTS, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LTS, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GES, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LES, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GTU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LTU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GEU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LEU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_EQF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_NEF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GTF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LTF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GEF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LEF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_JMP, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_JMPF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_JMPT, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_CALL, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_RET, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_END, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SYS, res)


  return 0;
  
}


#define RYVM_OPCODE_STR_REP(op) case RYVM_CON(RYVM_OP_, op): return RYVM_STR(op);

const char * ryvm_opcode_op_to_str(enum ryvm_opcode op) {
  switch (op) {
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_NOP)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MOV)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LDR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_PCA)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LDI)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_STR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_PUSH)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_POP)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_ADD)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SUB)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MUL)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MULU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_DIV)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_DIVU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MOD)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MODU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_ADDF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SUBF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MULF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_DIVF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MODF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_AND)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_OR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_XOR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_NOT)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SHL)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SHR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_BIC)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_EQ)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_NE)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GTS)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LTS)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GES)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LES)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GTU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LTU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GEU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LEU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_EQF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_NEF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GTF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LTF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GEF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LEF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_JMP)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_JMPF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_JMPT)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_CALL)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_RET)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_END)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SYS)
    default: assert(0);
  }
  return NULL;
}

#define RYVM_OPCODE_ARITY_MACRO(op, num) case RYVM_CON(RYVM_OP_, op): return num;

uint8_t ryvm_opcode_get_arity(enum ryvm_opcode op) {
  switch(op) {
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_NOP, 0) 
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_MOV, 2) 
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LDR, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_PCA, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LDI, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_STR, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_PUSH, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_POP, 1)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_ADD, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_SUB, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_MUL, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_MULU, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_DIV, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_DIVU, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_MOD, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_MODU, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_ADDF, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_SUBF, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_MULF, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_DIVF, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_MODF, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_AND, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_OR, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_XOR, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_NOT, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_SHL, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_SHR, 3)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_BIC, 1)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_EQ, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_NE, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_GTS, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LTS, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_GES, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LES, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_GTU, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LTU, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_GEU, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LEU, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_EQF, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_NEF, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_GTF, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LTF, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_GEF, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_LEF, 2)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_JMP, 1)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_JMPF, 1)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_JMPT, 1)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_CALL, 1)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_RET, 0)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_END, 1)
    RYVM_OPCODE_ARITY_MACRO(RYVM_OP_STR_SYS, 0)
    default: assert(0);

  }
}
