#include "opcodes.h"
#include <string.h>
#include <assert.h>
#include "helper.h"


//I don't like macros, but because I'm lazy,
//we are using macro wizardtry so that if we rename our opcodes,
//we can simply change one of the RYVM_OP_STR_... macros rather than
//going to both the str_to_op and op_to_str functions.


#define RYVM_OP_STR_LDA LDA
#define RYVM_OP_STR_PCR PCR
#define RYVM_OP_STR_LDI LDI
#define RYVM_OP_STR_STR STR
#define RYVM_OP_STR_FXFP FXFP
#define RYVM_OP_STR_FPFX FPFX
#define RYVM_OP_STR_ADDI ADDI
#define RYVM_OP_STR_SUBI SUBI
#define RYVM_OP_STR_ADD ADD
#define RYVM_OP_STR_SUB SUB
#define RYVM_OP_STR_MUL MUL
#define RYVM_OP_STR_MULU MULU
#define RYVM_OP_STR_DIV DIV
#define RYVM_OP_STR_DIVU DIVU
#define RYVM_OP_STR_REM REM
#define RYVM_OP_STR_REMU REMU
#define RYVM_OP_STR_ADDF ADDF
#define RYVM_OP_STR_SUBF SUBF
#define RYVM_OP_STR_MULF MULF
#define RYVM_OP_STR_DIVF DIVF
#define RYVM_OP_STR_REMF REMF
#define RYVM_OP_STR_AND AND
#define RYVM_OP_STR_OR OR
#define RYVM_OP_STR_XOR XOR
#define RYVM_OP_STR_XORI XORI
#define RYVM_OP_STR_SHL SHL
#define RYVM_OP_STR_SHR SHR
#define RYVM_OP_STR_BIC BIC
#define RYVM_OP_STR_EQ EQ
#define RYVM_OP_STR_NE NE
#define RYVM_OP_STR_GTS GTS
#define RYVM_OP_STR_LTS LTS
#define RYVM_OP_STR_GES GES
#define RYVM_OP_STR_LES LES
#define RYVM_OP_STR_GTU GTU
#define RYVM_OP_STR_LTU LTU
#define RYVM_OP_STR_GEU GEU
#define RYVM_OP_STR_LEU LEU
#define RYVM_OP_STR_GTF GTF
#define RYVM_OP_STR_LTF LTF
#define RYVM_OP_STR_GEF GEF
#define RYVM_OP_STR_LEF LEF
#define RYVM_OP_STR_B B
#define RYVM_OP_STR_BZ BZ
#define RYVM_OP_STR_BNZ BNZ
#define RYVM_OP_STR_BR BR
#define RYVM_OP_STR_BL BL
#define RYVM_OP_STR_BLR BLR
#define RYVM_OP_STR_SYS SYS





#define RYVM_OPCODE_STR(s, op, res) if(strcmp(s, RYVM_STR(op)) == 0) { *code = RYVM_CON(RYVM_OP_, op); return 1;}

int ryvm_opcode_str_to_op(const char *s, enum ryvm_opcode *code) {
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LDA, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_PCR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LDI, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_STR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LDI, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_STR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_ADDI, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SUBI, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_ADD, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SUB, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MUL, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MULU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_DIV, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_DIVU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_REM, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_REMU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_ADDF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SUBF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_MULF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_DIVF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_REMF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_AND, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_OR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_XOR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_XORI, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SHL, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SHR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_BIC, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_EQ, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_NE, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GTS, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LTS, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GES, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LES, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GTU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LTU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GEU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LEU, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GTF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LTF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_GEF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_LEF, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_B, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_BZ, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_BNZ, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_BR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_BL, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_BLR, res)
  RYVM_OPCODE_STR(s, RYVM_OP_STR_SYS, res)


  return 0;
  
}


#define RYVM_OPCODE_STR_REP(op) case RYVM_CON(RYVM_OP_, op): return RYVM_STR(op);

const char * ryvm_opcode_op_to_str(enum ryvm_opcode op) {
  switch (op) {
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LDA)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_PCR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LDI)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_STR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_FXFP)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_FPFX)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_ADDI)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SUBI)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_ADD)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SUB)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MUL)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MULU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_DIV)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_DIVU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_REM)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_REMU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_ADDF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SUBF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_MULF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_DIVF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_REMF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_AND)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_OR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_XOR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_XORI)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SHL)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SHR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_BIC)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_EQ)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_NE)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GTS)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LTS)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GES)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LES)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GTU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LTU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GEU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LEU)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GTF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LTF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_GEF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_LEF)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_B)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_BZ)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_BNZ)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_BR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_BL)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_BLR)
    RYVM_OPCODE_STR_REP(RYVM_OP_STR_SYS)
    default: assert(0);
  }
  return NULL;
}

#define RYVM_OPCODE_ARITY_MACRO(op, num) case RYVM_CON(RYVM_OP_, op): return num;

#define RYVM_MACRO_OPCODE_FORMAT(op, format) case RYVM_CON(RYVM_OP_, op): return format;

enum ryvm_ins_format ryvm_opcode_get_ins_format(enum ryvm_opcode op) {
  switch(op) {
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LDA,  RYVM_INS_FORMAT_R2) 
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_PCR,  RYVM_INS_FORMAT_R1) 
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LDI,  RYVM_INS_FORMAT_R1)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_STR,  RYVM_INS_FORMAT_R2)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_FXFP, RYVM_INS_FORMAT_R2)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_FPFX, RYVM_INS_FORMAT_R2)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_ADDI, RYVM_INS_FORMAT_R2)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_SUBI, RYVM_INS_FORMAT_R2)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_ADD,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_SUB,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_MUL,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_MULU, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_DIV,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_DIVU, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_REM,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_REMU, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_ADDF, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_SUBF, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_MULF, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_DIVF, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_REMF, RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_AND,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_OR,   RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_XOR,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_XORI, RYVM_INS_FORMAT_R2)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_SHL,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_SHR,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_BIC,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_EQ,   RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_NE,   RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_GTS,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LTS,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_GES,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LES,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_GTU,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LTU,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_GEU,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LEU,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_GTF,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LTF,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_GEF,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_LEF,  RYVM_INS_FORMAT_R3)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_B,    RYVM_INS_FORMAT_R0)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_BZ,   RYVM_INS_FORMAT_R1)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_BNZ,  RYVM_INS_FORMAT_R1)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_BR,   RYVM_INS_FORMAT_R1)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_BL,   RYVM_INS_FORMAT_R1)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_BLR,  RYVM_INS_FORMAT_R2)
    RYVM_MACRO_OPCODE_FORMAT(RYVM_OP_STR_SYS,  RYVM_INS_FORMAT_R0)
    default: assert(0);
  }
  return -1;
}

